import { readFileSync, readdirSync, statSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

// Pattern-based fixes for Spanish text where U+FFFD replaced accented characters
const contextualFixes: [RegExp, string][] = [
  // Common word patterns with replacement character
  [/Rep�blica/g, 'República'],
  [/REP�BLICA/g, 'REPÚBLICA'],
  [/p�blica/g, 'pública'],
  [/P�BLICA/g, 'PÚBLICA'],
  [/Art�culo/g, 'Artículo'],
  [/ART�CULO/g, 'ARTÍCULO'],
  [/art�culo/g, 'artículo'],
  [/�nico/g, 'único'],
  [/�NICO/g, 'ÚNICO'],
  [/�NICA/g, 'ÚNICA'],
  [/�nica/g, 'única'],
  [/Comun�quese/g, 'Comuníquese'],
  [/COMUN�QUESE/g, 'COMUNÍQUESE'],
  [/comun�quese/g, 'comuníquese'],
  [/se�or/g, 'señor'],
  [/SE�OR/g, 'SEÑOR'],
  [/se�ora/g, 'señora'],
  [/SE�ORA/g, 'SEÑORA'],
  [/a�o/g, 'año'],
  [/A�O/g, 'AÑO'],
  [/a�os/g, 'años'],
  [/A�OS/g, 'AÑOS'],
  [/d�a/g, 'día'],
  [/D�A/g, 'DÍA'],
  [/d�as/g, 'días'],
  [/D�AS/g, 'DÍAS'],
  [/n�mero/g, 'número'],
  [/N�MERO/g, 'NÚMERO'],
  [/N�mero/g, 'Número'],
  [/p�rrafo/g, 'párrafo'],
  [/P�RRAFO/g, 'PÁRRAFO'],
  [/cap�tulo/g, 'capítulo'],
  [/CAP�TULO/g, 'CAPÍTULO'],
  [/Cap�tulo/g, 'Capítulo'],
  [/t�tulo/g, 'título'],
  [/T�TULO/g, 'TÍTULO'],
  [/T�tulo/g, 'Título'],
  [/secci�n/g, 'sección'],
  [/SECCI�N/g, 'SECCIÓN'],
  [/Secci�n/g, 'Sección'],
  [/disposici�n/g, 'disposición'],
  [/DISPOSICI�N/g, 'DISPOSICIÓN'],
  [/Disposici�n/g, 'Disposición'],
  [/modificaci�n/g, 'modificación'],
  [/MODIFICACI�N/g, 'MODIFICACIÓN'],
  [/derogaci�n/g, 'derogación'],
  [/DEROGACI�N/g, 'DEROGACIÓN'],
  [/promulgaci�n/g, 'promulgación'],
  [/PROMULGACI�N/g, 'PROMULGACIÓN'],
  [/publicaci�n/g, 'publicación'],
  [/PUBLICACI�N/g, 'PUBLICACIÓN'],
  [/constituci�n/g, 'constitución'],
  [/CONSTITUCI�N/g, 'CONSTITUCIÓN'],
  [/Constituci�n/g, 'Constitución'],
  [/legislaci�n/g, 'legislación'],
  [/LEGISLACI�N/g, 'LEGISLACIÓN'],
  [/resoluci�n/g, 'resolución'],
  [/RESOLUCI�N/g, 'RESOLUCIÓN'],
  [/Resoluci�n/g, 'Resolución'],
  [/administraci�n/g, 'administración'],
  [/ADMINISTRACI�N/g, 'ADMINISTRACIÓN'],
  [/Administraci�n/g, 'Administración'],
  [/organizaci�n/g, 'organización'],
  [/ORGANIZACI�N/g, 'ORGANIZACIÓN'],
  [/Organizaci�n/g, 'Organización'],
  [/informaci�n/g, 'información'],
  [/INFORMACI�N/g, 'INFORMACIÓN'],
  [/Informaci�n/g, 'Información'],
  [/educaci�n/g, 'educación'],
  [/EDUCACI�N/g, 'EDUCACIÓN'],
  [/Educaci�n/g, 'Educación'],
  [/protecci�n/g, 'protección'],
  [/PROTECCI�N/g, 'PROTECCIÓN'],
  [/Protecci�n/g, 'Protección'],
  [/evaluaci�n/g, 'evaluación'],
  [/EVALUACI�N/g, 'EVALUACIÓN'],
  [/Evaluaci�n/g, 'Evaluación'],
  [/regulaci�n/g, 'regulación'],
  [/REGULACI�N/g, 'REGULACIÓN'],
  [/Regulaci�n/g, 'Regulación'],
  [/acci�n/g, 'acción'],
  [/ACCI�N/g, 'ACCIÓN'],
  [/Acci�n/g, 'Acción'],
  [/funci�n/g, 'función'],
  [/FUNCI�N/g, 'FUNCIÓN'],
  [/Funci�n/g, 'Función'],
  [/atenci�n/g, 'atención'],
  [/ATENCI�N/g, 'ATENCIÓN'],
  [/Atenci�n/g, 'Atención'],
  [/intenci�n/g, 'intención'],
  [/INTENCI�N/g, 'INTENCIÓN'],
  [/relaci�n/g, 'relación'],
  [/RELACI�N/g, 'RELACIÓN'],
  [/Relaci�n/g, 'Relación'],
  [/obligaci�n/g, 'obligación'],
  [/OBLIGACI�N/g, 'OBLIGACIÓN'],
  [/Obligaci�n/g, 'Obligación'],
  [/aplicaci�n/g, 'aplicación'],
  [/APLICACI�N/g, 'APLICACIÓN'],
  [/Aplicaci�n/g, 'Aplicación'],
  [/aprobaci�n/g, 'aprobación'],
  [/APROBACI�N/g, 'APROBACIÓN'],
  [/excepci�n/g, 'excepción'],
  [/EXCEPCI�N/g, 'EXCEPCIÓN'],
  [/instituci�n/g, 'institución'],
  [/INSTITUCI�N/g, 'INSTITUCIÓN'],
  [/Instituci�n/g, 'Institución'],
  [/naci�n/g, 'nación'],
  [/NACI�N/g, 'NACIÓN'],
  [/Naci�n/g, 'Nación'],
  [/opci�n/g, 'opción'],
  [/OPCI�N/g, 'OPCIÓN'],
  [/pensi�n/g, 'pensión'],
  [/PENSI�N/g, 'PENSIÓN'],
  [/Pensi�n/g, 'Pensión'],
  [/versi�n/g, 'versión'],
  [/VERSI�N/g, 'VERSIÓN'],
  [/Versi�n/g, 'Versión'],
  [/prisi�n/g, 'prisión'],
  [/PRISI�N/g, 'PRISIÓN'],
  [/decisi�n/g, 'decisión'],
  [/DECISI�N/g, 'DECISIÓN'],
  [/misi�n/g, 'misión'],
  [/MISI�N/g, 'MISIÓN'],
  [/comisi�n/g, 'comisión'],
  [/COMISI�N/g, 'COMISIÓN'],
  [/Comisi�n/g, 'Comisión'],
  [/emisi�n/g, 'emisión'],
  [/EMISI�N/g, 'EMISIÓN'],
  [/admisi�n/g, 'admisión'],
  [/ADMISI�N/g, 'ADMISIÓN'],
  [/permisi�n/g, 'permisión'],
  [/revisi�n/g, 'revisión'],
  [/REVISI�N/g, 'REVISIÓN'],
  [/provisi�n/g, 'provisión'],
  [/PROVISI�N/g, 'PROVISIÓN'],
  [/previsi�n/g, 'previsión'],
  [/PREVISI�N/g, 'PREVISIÓN'],
  [/supervisi�n/g, 'supervisión'],
  [/SUPERVISI�N/g, 'SUPERVISIÓN'],
  [/fisi�n/g, 'fisión'],
  [/divisi�n/g, 'división'],
  [/DIVISI�N/g, 'DIVISIÓN'],
  [/Divisi�n/g, 'División'],
  [/precisi�n/g, 'precisión'],
  [/PRECISI�N/g, 'PRECISIÓN'],
  [/ocasi�n/g, 'ocasión'],
  [/OCASI�N/g, 'OCASIÓN'],
  [/invasi�n/g, 'invasión'],
  [/INVASI�N/g, 'INVASIÓN'],
  [/evasi�n/g, 'evasión'],
  [/EVASI�N/g, 'EVASIÓN'],
  [/conclusi�n/g, 'conclusión'],
  [/CONCLUSI�N/g, 'CONCLUSIÓN'],
  [/inclusi�n/g, 'inclusión'],
  [/INCLUSI�N/g, 'INCLUSIÓN'],
  [/exclusi�n/g, 'exclusión'],
  [/EXCLUSI�N/g, 'EXCLUSIÓN'],
  [/confusi�n/g, 'confusión'],
  [/CONFUSI�N/g, 'CONFUSIÓN'],
  [/difusi�n/g, 'difusión'],
  [/DIFUSI�N/g, 'DIFUSIÓN'],
  [/ilusi�n/g, 'ilusión'],
  [/ILUSI�N/g, 'ILUSIÓN'],
  [/conclisi�n/g, 'conclusión'],
  [/transici�n/g, 'transición'],
  [/TRANSICI�N/g, 'TRANSICIÓN'],
  [/Transici�n/g, 'Transición'],
  [/condici�n/g, 'condición'],
  [/CONDICI�N/g, 'CONDICIÓN'],
  [/Condici�n/g, 'Condición'],
  [/adici�n/g, 'adición'],
  [/ADICI�N/g, 'ADICIÓN'],
  [/tradici�n/g, 'tradición'],
  [/TRADICI�N/g, 'TRADICIÓN'],
  [/definici�n/g, 'definición'],
  [/DEFINICI�N/g, 'DEFINICIÓN'],
  [/Definici�n/g, 'Definición'],
  [/prohibici�n/g, 'prohibición'],
  [/PROHIBICI�N/g, 'PROHIBICIÓN'],
  [/Prohibici�n/g, 'Prohibición'],
  [/exhibici�n/g, 'exhibición'],
  [/jurisdicci�n/g, 'jurisdicción'],
  [/JURISDICCI�N/g, 'JURISDICCIÓN'],
  [/Jurisdicci�n/g, 'Jurisdicción'],
  [/direcci�n/g, 'dirección'],
  [/DIRECCI�N/g, 'DIRECCIÓN'],
  [/Direcci�n/g, 'Dirección'],
  [/elecci�n/g, 'elección'],
  [/ELECCI�N/g, 'ELECCIÓN'],
  [/Elecci�n/g, 'Elección'],
  [/recolecci�n/g, 'recolección'],
  [/selecci�n/g, 'selección'],
  [/SELECCI�N/g, 'SELECCIÓN'],
  [/Selecci�n/g, 'Selección'],
  [/colecci�n/g, 'colección'],
  [/COLECCI�N/g, 'COLECCIÓN'],
  [/infecci�n/g, 'infección'],
  [/INFECCI�N/g, 'INFECCIÓN'],
  [/protecci�n/g, 'protección'],
  [/PROTECCI�N/g, 'PROTECCIÓN'],
  [/Protecci�n/g, 'Protección'],
  [/inspecci�n/g, 'inspección'],
  [/INSPECCI�N/g, 'INSPECCIÓN'],
  [/Inspecci�n/g, 'Inspección'],
  [/construcci�n/g, 'construcción'],
  [/CONSTRUCCI�N/g, 'CONSTRUCCIÓN'],
  [/Construcci�n/g, 'Construcción'],
  [/destrucci�n/g, 'destrucción'],
  [/DESTRUCCI�N/g, 'DESTRUCCIÓN'],
  [/instrucci�n/g, 'instrucción'],
  [/INSTRUCCI�N/g, 'INSTRUCCIÓN'],
  [/Instrucci�n/g, 'Instrucción'],
  [/producci�n/g, 'producción'],
  [/PRODUCCI�N/g, 'PRODUCCIÓN'],
  [/Producci�n/g, 'Producción'],
  [/reducci�n/g, 'reducción'],
  [/REDUCCI�N/g, 'REDUCCIÓN'],
  [/introducci�n/g, 'introducción'],
  [/INTRODUCCI�N/g, 'INTRODUCCIÓN'],
  [/traducci�n/g, 'traducción'],
  [/conducci�n/g, 'conducción'],
  [/seducci�n/g, 'seducción'],
  [/ejecuci�n/g, 'ejecución'],
  [/EJECUCI�N/g, 'EJECUCIÓN'],
  [/Ejecuci�n/g, 'Ejecución'],
  [/persecuci�n/g, 'persecución'],
  [/PERSECUCI�N/g, 'PERSECUCIÓN'],
  [/contribuci�n/g, 'contribución'],
  [/CONTRIBUCI�N/g, 'CONTRIBUCIÓN'],
  [/Contribuci�n/g, 'Contribución'],
  [/atribuci�n/g, 'atribución'],
  [/ATRIBUCI�N/g, 'ATRIBUCIÓN'],
  [/Atribuci�n/g, 'Atribución'],
  [/distribuci�n/g, 'distribución'],
  [/DISTRIBUCI�N/g, 'DISTRIBUCIÓN'],
  [/Distribuci�n/g, 'Distribución'],
  [/retribuci�n/g, 'retribución'],
  [/RETRIBUCI�N/g, 'RETRIBUCIÓN'],
  [/soluci�n/g, 'solución'],
  [/SOLUCI�N/g, 'SOLUCIÓN'],
  [/Soluci�n/g, 'Solución'],
  [/resoluci�n/g, 'resolución'],
  [/absoluci�n/g, 'absolución'],
  [/disoluci�n/g, 'disolución'],
  [/revoluci�n/g, 'revolución'],
  [/evoluci�n/g, 'evolución'],
  [/EVOLUCI�N/g, 'EVOLUCIÓN'],
  [/devoluci�n/g, 'devolución'],
  [/DEVOLUCI�N/g, 'DEVOLUCIÓN'],
  [/contaminaci�n/g, 'contaminación'],
  [/CONTAMINACI�N/g, 'CONTAMINACIÓN'],
  [/determinaci�n/g, 'determinación'],
  [/DETERMINACI�N/g, 'DETERMINACIÓN'],
  [/terminaci�n/g, 'terminación'],
  [/TERMINACI�N/g, 'TERMINACIÓN'],
  [/denominaci�n/g, 'denominación'],
  [/DENOMINACI�N/g, 'DENOMINACIÓN'],
  [/eliminaci�n/g, 'eliminación'],
  [/ELIMINACI�N/g, 'ELIMINACIÓN'],
  [/iluminaci�n/g, 'iluminación'],
  [/ILUMINACI�N/g, 'ILUMINACIÓN'],
  [/nominaci�n/g, 'nominación'],
  [/coordinaci�n/g, 'coordinación'],
  [/COORDINACI�N/g, 'COORDINACIÓN'],
  [/Coordinaci�n/g, 'Coordinación'],
  [/subordinaci�n/g, 'subordinación'],
  [/culminaci�n/g, 'culminación'],
  [/discriminaci�n/g, 'discriminación'],
  [/DISCRIMINACI�N/g, 'DISCRIMINACIÓN'],
  [/Discriminaci�n/g, 'Discriminación'],
  [/incriminaci�n/g, 'incriminación'],
  [/combinaci�n/g, 'combinación'],
  [/COMBINACI�N/g, 'COMBINACIÓN'],
  [/dominaci�n/g, 'dominación'],
  [/examinaci�n/g, 'examinación'],
  [/reclamaci�n/g, 'reclamación'],
  [/RECLAMACI�N/g, 'RECLAMACIÓN'],
  [/Reclamaci�n/g, 'Reclamación'],
  [/proclamaci�n/g, 'proclamación'],
  [/PROCLAMACI�N/g, 'PROCLAMACIÓN'],
  [/exclamaci�n/g, 'exclamación'],
  [/declaraci�n/g, 'declaración'],
  [/DECLARACI�N/g, 'DECLARACIÓN'],
  [/Declaraci�n/g, 'Declaración'],
  [/alteraci�n/g, 'alteración'],
  [/ALTERACI�N/g, 'ALTERACIÓN'],
  [/consideraci�n/g, 'consideración'],
  [/CONSIDERACI�N/g, 'CONSIDERACIÓN'],
  [/Consideraci�n/g, 'Consideración'],
  [/remuneraci�n/g, 'remuneración'],
  [/REMUNERACI�N/g, 'REMUNERACIÓN'],
  [/Remuneraci�n/g, 'Remuneración'],
  [/generaci�n/g, 'generación'],
  [/GENERACI�N/g, 'GENERACIÓN'],
  [/Generaci�n/g, 'Generación'],
  [/regeneraci�n/g, 'regeneración'],
  [/degeneraci�n/g, 'degeneración'],
  [/operaci�n/g, 'operación'],
  [/OPERACI�N/g, 'OPERACIÓN'],
  [/Operaci�n/g, 'Operación'],
  [/cooperaci�n/g, 'cooperación'],
  [/COOPERACI�N/g, 'COOPERACIÓN'],
  [/Cooperaci�n/g, 'Cooperación'],
  [/recuperaci�n/g, 'recuperación'],
  [/RECUPERACI�N/g, 'RECUPERACIÓN'],
  [/Recuperaci�n/g, 'Recuperación'],
  [/liberaci�n/g, 'liberación'],
  [/LIBERACI�N/g, 'LIBERACIÓN'],
  [/Liberaci�n/g, 'Liberación'],
  [/deliberaci�n/g, 'deliberación'],
  [/DELIBERACI�N/g, 'DELIBERACIÓN'],
  [/exoneraci�n/g, 'exoneración'],
  [/EXONERACI�N/g, 'EXONERACIÓN'],
  [/Exoneraci�n/g, 'Exoneración'],
  [/federaci�n/g, 'federación'],
  [/FEDERACI�N/g, 'FEDERACIÓN'],
  [/Federaci�n/g, 'Federación'],
  [/confederaci�n/g, 'confederación'],
  [/toleraci�n/g, 'toleración'],
  [/aceleraci�n/g, 'aceleración'],
  [/moderaci�n/g, 'moderación'],
  [/ponderaci�n/g, 'ponderación'],
  [/reiteraci�n/g, 'reiteración'],
  [/REITERACI�N/g, 'REITERACIÓN'],
  [/numeraci�n/g, 'numeración'],
  [/NUMERACI�N/g, 'NUMERACIÓN'],
  [/enumeraci�n/g, 'enumeración'],
  [/ENUMERACI�N/g, 'ENUMERACIÓN'],
  [/comparaci�n/g, 'comparación'],
  [/COMPARACI�N/g, 'COMPARACIÓN'],
  [/preparaci�n/g, 'preparación'],
  [/PREPARACI�N/g, 'PREPARACIÓN'],
  [/Preparaci�n/g, 'Preparación'],
  [/separaci�n/g, 'separación'],
  [/SEPARACI�N/g, 'SEPARACIÓN'],
  [/reparaci�n/g, 'reparación'],
  [/REPARACI�N/g, 'REPARACIÓN'],
  [/Reparaci�n/g, 'Reparación'],
  [/esperaci�n/g, 'esperación'],
  [/exasperaci�n/g, 'exasperación'],
  [/desesperaci�n/g, 'desesperación'],
  [/aspiraci�n/g, 'aspiración'],
  [/inspiraci�n/g, 'inspiración'],
  [/respiraci�n/g, 'respiración'],
  [/conspiraci�n/g, 'conspiración'],
  [/expiraci�n/g, 'expiración'],
  [/EXPIRACI�N/g, 'EXPIRACIÓN'],
  [/admiraci�n/g, 'admiración'],
  [/configuraci�n/g, 'configuración'],
  [/CONFIGURACI�N/g, 'CONFIGURACIÓN'],
  [/Configuraci�n/g, 'Configuración'],
  [/elaboraci�n/g, 'elaboración'],
  [/ELABORACI�N/g, 'ELABORACIÓN'],
  [/Elaboraci�n/g, 'Elaboración'],
  [/colaboraci�n/g, 'colaboración'],
  [/COLABORACI�N/g, 'COLABORACIÓN'],
  [/Colaboraci�n/g, 'Colaboración'],
  [/decoraci�n/g, 'decoración'],
  [/DECORACI�N/g, 'DECORACIÓN'],
  [/incorporaci�n/g, 'incorporación'],
  [/INCORPORACI�N/g, 'INCORPORACIÓN'],
  [/Incorporaci�n/g, 'Incorporación'],
  [/corporaci�n/g, 'corporación'],
  [/CORPORACI�N/g, 'CORPORACIÓN'],
  [/Corporaci�n/g, 'Corporación'],
  [/exploraci�n/g, 'exploración'],
  [/EXPLORACI�N/g, 'EXPLORACIÓN'],
  [/valoraci�n/g, 'valoración'],
  [/VALORACI�N/g, 'VALORACIÓN'],
  [/Valoraci�n/g, 'Valoración'],
  [/mejoraci�n/g, 'mejoración'],
  [/autorizaci�n/g, 'autorización'],
  [/AUTORIZACI�N/g, 'AUTORIZACIÓN'],
  [/Autorizaci�n/g, 'Autorización'],
  [/caracterizaci�n/g, 'caracterización'],
  [/CARACTERIZACI�N/g, 'CARACTERIZACIÓN'],
  [/actualizaci�n/g, 'actualización'],
  [/ACTUALIZACI�N/g, 'ACTUALIZACIÓN'],
  [/Actualizaci�n/g, 'Actualización'],
  [/legalizaci�n/g, 'legalización'],
  [/LEGALIZACI�N/g, 'LEGALIZACIÓN'],
  [/realizaci�n/g, 'realización'],
  [/REALIZACI�N/g, 'REALIZACIÓN'],
  [/Realizaci�n/g, 'Realización'],
  [/nacionalizaci�n/g, 'nacionalización'],
  [/NACIONALIZACI�N/g, 'NACIONALIZACIÓN'],
  [/racionalizaci�n/g, 'racionalización'],
  [/RACIONALIZACI�N/g, 'RACIONALIZACIÓN'],
  [/normalizaci�n/g, 'normalización'],
  [/NORMALIZACI�N/g, 'NORMALIZACIÓN'],
  [/formalizaci�n/g, 'formalización'],
  [/FORMALIZACI�N/g, 'FORMALIZACIÓN'],
  [/Formalizaci�n/g, 'Formalización'],
  [/localizaci�n/g, 'localización'],
  [/LOCALIZACI�N/g, 'LOCALIZACIÓN'],
  [/fiscalizaci�n/g, 'fiscalización'],
  [/FISCALIZACI�N/g, 'FISCALIZACIÓN'],
  [/Fiscalizaci�n/g, 'Fiscalización'],
  [/capitalizaci�n/g, 'capitalización'],
  [/CAPITALIZACI�N/g, 'CAPITALIZACIÓN'],
  [/totalizaci�n/g, 'totalización'],
  [/utilizaci�n/g, 'utilización'],
  [/UTILIZACI�N/g, 'UTILIZACIÓN'],
  [/Utilizaci�n/g, 'Utilización'],
  [/fertilizaci�n/g, 'fertilización'],
  [/esterilizaci�n/g, 'esterilización'],
  [/movilizaci�n/g, 'movilización'],
  [/MOVILIZACI�N/g, 'MOVILIZACIÓN'],
  [/civilizaci�n/g, 'civilización'],
  [/inmovilizaci�n/g, 'inmovilización'],
  [/organizaci�n/g, 'organización'],
  [/reorganizaci�n/g, 'reorganización'],
  [/REORGANIZACI�N/g, 'REORGANIZACIÓN'],
  [/indemnizaci�n/g, 'indemnización'],
  [/INDEMNIZACI�N/g, 'INDEMNIZACIÓN'],
  [/Indemnizaci�n/g, 'Indemnización'],
  [/colonizaci�n/g, 'colonización'],
  [/armonizaci�n/g, 'armonización'],
  [/ARMONIZACI�N/g, 'ARMONIZACIÓN'],
  [/modernizaci�n/g, 'modernización'],
  [/MODERNIZACI�N/g, 'MODERNIZACIÓN'],
  [/Modernizaci�n/g, 'Modernización'],
  [/sincronizaci�n/g, 'sincronización'],
  [/inmunizaci�n/g, 'inmunización'],
  [/comunicaci�n/g, 'comunicación'],
  [/COMUNICACI�N/g, 'COMUNICACIÓN'],
  [/Comunicaci�n/g, 'Comunicación'],
  [/excomunicaci�n/g, 'excomunicación'],
  [/justificaci�n/g, 'justificación'],
  [/JUSTIFICACI�N/g, 'JUSTIFICACIÓN'],
  [/Justificaci�n/g, 'Justificación'],
  [/calificaci�n/g, 'calificación'],
  [/CALIFICACI�N/g, 'CALIFICACIÓN'],
  [/Calificaci�n/g, 'Calificación'],
  [/ratificaci�n/g, 'ratificación'],
  [/RATIFICACI�N/g, 'RATIFICACIÓN'],
  [/Ratificaci�n/g, 'Ratificación'],
  [/rectificaci�n/g, 'rectificación'],
  [/RECTIFICACI�N/g, 'RECTIFICACIÓN'],
  [/Rectificaci�n/g, 'Rectificación'],
  [/notificaci�n/g, 'notificación'],
  [/NOTIFICACI�N/g, 'NOTIFICACIÓN'],
  [/Notificaci�n/g, 'Notificación'],
  [/certificaci�n/g, 'certificación'],
  [/CERTIFICACI�N/g, 'CERTIFICACIÓN'],
  [/Certificaci�n/g, 'Certificación'],
  [/gratificaci�n/g, 'gratificación'],
  [/GRATIFICACI�N/g, 'GRATIFICACIÓN'],
  [/Gratificaci�n/g, 'Gratificación'],
  [/modificaci�n/g, 'modificación'],
  [/codificaci�n/g, 'codificación'],
  [/CODIFICACI�N/g, 'CODIFICACIÓN'],
  [/verificaci�n/g, 'verificación'],
  [/VERIFICACI�N/g, 'VERIFICACIÓN'],
  [/Verificaci�n/g, 'Verificación'],
  [/purificaci�n/g, 'purificación'],
  [/clasificaci�n/g, 'clasificación'],
  [/CLASIFICACI�N/g, 'CLASIFICACIÓN'],
  [/Clasificaci�n/g, 'Clasificación'],
  [/especificaci�n/g, 'especificación'],
  [/ESPECIFICACI�N/g, 'ESPECIFICACIÓN'],
  [/Especificaci�n/g, 'Especificación'],
  [/planificaci�n/g, 'planificación'],
  [/PLANIFICACI�N/g, 'PLANIFICACIÓN'],
  [/Planificaci�n/g, 'Planificación'],
  [/identificaci�n/g, 'identificación'],
  [/IDENTIFICACI�N/g, 'IDENTIFICACIÓN'],
  [/Identificaci�n/g, 'Identificación'],
  [/significaci�n/g, 'significación'],
  [/tipificaci�n/g, 'tipificación'],
  [/TIPIFICACI�N/g, 'TIPIFICACIÓN'],
  [/Tipificaci�n/g, 'Tipificación'],
  [/simplificaci�n/g, 'simplificación'],
  [/SIMPLIFICACI�N/g, 'SIMPLIFICACIÓN'],
  [/amplificaci�n/g, 'amplificación'],
  [/ejemplificaci�n/g, 'ejemplificación'],
  [/vinificaci�n/g, 'vinificación'],
  [/bonificaci�n/g, 'bonificación'],
  [/BONIFICACI�N/g, 'BONIFICACIÓN'],
  [/Bonificaci�n/g, 'Bonificación'],
  [/personificaci�n/g, 'personificación'],
  [/unificaci�n/g, 'unificación'],
  [/UNIFICACI�N/g, 'UNIFICACIÓN'],
  [/Unificaci�n/g, 'Unificación'],
  [/reunificaci�n/g, 'reunificación'],
  [/cuantificaci�n/g, 'cuantificación'],
  [/intensificaci�n/g, 'intensificación'],
  [/diversificaci�n/g, 'diversificación'],
  [/DIVERSIFICACI�N/g, 'DIVERSIFICACIÓN'],
  [/dosificaci�n/g, 'dosificación'],
  [/falsificaci�n/g, 'falsificación'],
  [/FALSIFICACI�N/g, 'FALSIFICACIÓN'],
  [/masificaci�n/g, 'masificación'],
  [/electrificaci�n/g, 'electrificación'],
  [/ELECTRIFICACI�N/g, 'ELECTRIFICACIÓN'],
  [/Electrificaci�n/g, 'Electrificación'],
  [/glorificaci�n/g, 'glorificación'],
  [/publicaci�n/g, 'publicación'],
  [/aplicaci�n/g, 'aplicación'],
  [/replicaci�n/g, 'replicación'],
  [/duplicaci�n/g, 'duplicación'],
  [/DUPLICACI�N/g, 'DUPLICACIÓN'],
  [/complicaci�n/g, 'complicación'],
  [/implicaci�n/g, 'implicación'],
  [/explicaci�n/g, 'explicación'],
  [/EXPLICACI�N/g, 'EXPLICACIÓN'],
  [/Explicaci�n/g, 'Explicación'],
  [/fabricaci�n/g, 'fabricación'],
  [/FABRICACI�N/g, 'FABRICACIÓN'],
  [/Fabricaci�n/g, 'Fabricación'],
  [/lubricaci�n/g, 'lubricación'],
  [/comunicaci�n/g, 'comunicación'],
  [/indicaci�n/g, 'indicación'],
  [/INDICACI�N/g, 'INDICACIÓN'],
  [/Indicaci�n/g, 'Indicación'],
  [/vindicaci�n/g, 'vindicación'],
  [/reivindicaci�n/g, 'reivindicación'],
  [/REIVINDICACI�N/g, 'REIVINDICACIÓN'],
  [/predicaci�n/g, 'predicación'],
  [/medicaci�n/g, 'medicación'],
  [/MEDICACI�N/g, 'MEDICACIÓN'],
  [/dedicaci�n/g, 'dedicación'],
  [/DEDICACI�N/g, 'DEDICACIÓN'],
  [/adjudicaci�n/g, 'adjudicación'],
  [/ADJUDICACI�N/g, 'ADJUDICACIÓN'],
  [/Adjudicaci�n/g, 'Adjudicación'],
  [/judicaci�n/g, 'judicación'],
  [/erradicaci�n/g, 'erradicación'],
  [/ERRADICACI�N/g, 'ERRADICACIÓN'],
  [/Erradicaci�n/g, 'Erradicación'],
  [/radicaci�n/g, 'radicación'],
  [/sindicaci�n/g, 'sindicación'],
  [/SINDICACI�N/g, 'SINDICACIÓN'],
  [/ubicaci�n/g, 'ubicación'],
  [/UBICACI�N/g, 'UBICACIÓN'],
  [/Ubicaci�n/g, 'Ubicación'],
  [/embarcaci�n/g, 'embarcación'],
  [/EMBARCACI�N/g, 'EMBARCACIÓN'],
  [/Embarcaci�n/g, 'Embarcación'],
  [/demarcaci�n/g, 'demarcación'],
  [/DEMARCACI�N/g, 'DEMARCACIÓN'],
  [/Demarcaci�n/g, 'Demarcación'],
  [/convocaci�n/g, 'convocación'],
  [/invocaci�n/g, 'invocación'],
  [/provocaci�n/g, 'provocación'],
  [/revocaci�n/g, 'revocación'],
  [/REVOCACI�N/g, 'REVOCACIÓN'],
  [/evocaci�n/g, 'evocación'],
  [/educaci�n/g, 'educación'],
  [/reeducaci�n/g, 'reeducación'],
  [/adecuaci�n/g, 'adecuación'],
  [/ADECUACI�N/g, 'ADECUACIÓN'],
  [/Adecuaci�n/g, 'Adecuación'],
  [/inadecuaci�n/g, 'inadecuación'],
  [/evacuaci�n/g, 'evacuación'],
  [/EVACUACI�N/g, 'EVACUACIÓN'],

  // Day names
  [/Mi�rcoles/g, 'Miércoles'],
  [/MI�RCOLES/g, 'MIÉRCOLES'],
  [/mi�rcoles/g, 'miércoles'],
  [/S�bado/g, 'Sábado'],
  [/S�BADO/g, 'SÁBADO'],
  [/s�bado/g, 'sábado'],

  // Month names
  [/Marzo/g, 'Marzo'], // Usually OK
  [/Febrero/g, 'Febrero'], // Usually OK

  // Common legal/government terms
  [/ley/g, 'ley'], // Usually OK, but check context
  [/Polic�a/g, 'Policía'],
  [/POLIC�A/g, 'POLICÍA'],
  [/polic�a/g, 'policía'],
  [/Ej�rcito/g, 'Ejército'],
  [/EJ�RCITO/g, 'EJÉRCITO'],
  [/ej�rcito/g, 'ejército'],
  [/C�digo/g, 'Código'],
  [/C�DIGO/g, 'CÓDIGO'],
  [/c�digo/g, 'código'],
  [/Jur�dico/g, 'Jurídico'],
  [/JUR�DICO/g, 'JURÍDICO'],
  [/jur�dico/g, 'jurídico'],
  [/jur�dica/g, 'jurídica'],
  [/Jur�dica/g, 'Jurídica'],
  [/JUR�DICA/g, 'JURÍDICA'],
  [/electr�nico/g, 'electrónico'],
  [/ELECTR�NICO/g, 'ELECTRÓNICO'],
  [/Electr�nico/g, 'Electrónico'],
  [/electr�nica/g, 'electrónica'],
  [/ELECTR�NICA/g, 'ELECTRÓNICA'],
  [/Electr�nica/g, 'Electrónica'],
  [/econ�mico/g, 'económico'],
  [/ECON�MICO/g, 'ECONÓMICO'],
  [/Econ�mico/g, 'Económico'],
  [/econ�mica/g, 'económica'],
  [/ECON�MICA/g, 'ECONÓMICA'],
  [/Econ�mica/g, 'Económica'],
  [/t�cnico/g, 'técnico'],
  [/T�CNICO/g, 'TÉCNICO'],
  [/T�cnico/g, 'Técnico'],
  [/t�cnica/g, 'técnica'],
  [/T�CNICA/g, 'TÉCNICA'],
  [/T�cnica/g, 'Técnica'],
  [/p�blico/g, 'público'],
  [/P�BLICO/g, 'PÚBLICO'],
  [/P�blico/g, 'Público'],
  [/Ministerio/g, 'Ministerio'], // Usually OK
  [/Ministro/g, 'Ministro'], // Usually OK
  [/ministro/g, 'ministro'], // Usually OK
  [/Legislativo/g, 'Legislativo'], // Usually OK
  [/LEGISLATIVO/g, 'LEGISLATIVO'], // Usually OK
  [/legislativo/g, 'legislativo'], // Usually OK
  [/r�gimen/g, 'régimen'],
  [/R�GIMEN/g, 'RÉGIMEN'],
  [/R�gimen/g, 'Régimen'],
  [/per�odo/g, 'período'],
  [/PER�ODO/g, 'PERÍODO'],
  [/Per�odo/g, 'Período'],
  [/pr�rroga/g, 'prórroga'],
  [/PR�RROGA/g, 'PRÓRROGA'],
  [/Pr�rroga/g, 'Prórroga'],
  [/tr�mite/g, 'trámite'],
  [/TR�MITE/g, 'TRÁMITE'],
  [/Tr�mite/g, 'Trámite'],
  [/m�ximo/g, 'máximo'],
  [/M�XIMO/g, 'MÁXIMO'],
  [/M�ximo/g, 'Máximo'],
  [/m�xima/g, 'máxima'],
  [/M�XIMA/g, 'MÁXIMA'],
  [/m�nimo/g, 'mínimo'],
  [/M�NIMO/g, 'MÍNIMO'],
  [/M�nimo/g, 'Mínimo'],
  [/m�nima/g, 'mínima'],
  [/M�NIMA/g, 'MÍNIMA'],
  [/�ltimo/g, 'último'],
  [/�LTIMO/g, 'ÚLTIMO'],
  [/�ltima/g, 'última'],
  [/�LTIMA/g, 'ÚLTIMA'],
  [/pr�ximo/g, 'próximo'],
  [/PR�XIMO/g, 'PRÓXIMO'],
  [/Pr�ximo/g, 'Próximo'],
  [/pr�xima/g, 'próxima'],
  [/PR�XIMA/g, 'PRÓXIMA'],
  [/Pr�xima/g, 'Próxima'],
  [/leg�timo/g, 'legítimo'],
  [/LEG�TIMO/g, 'LEGÍTIMO'],
  [/leg�tima/g, 'legítima'],
  [/LEG�TIMA/g, 'LEGÍTIMA'],
  [/ileg�timo/g, 'ilegítimo'],
  [/ILEG�TIMO/g, 'ILEGÍTIMO'],
  [/mar�timo/g, 'marítimo'],
  [/MAR�TIMO/g, 'MARÍTIMO'],
  [/Mar�timo/g, 'Marítimo'],
  [/mar�tima/g, 'marítima'],
  [/MAR�TIMA/g, 'MARÍTIMA'],
  [/Mar�tima/g, 'Marítima'],
  [/aer�dromo/g, 'aeródromo'],
  [/AER�DROMO/g, 'AERÓDROMO'],
  [/aut�nomo/g, 'autónomo'],
  [/AUT�NOMO/g, 'AUTÓNOMO'],
  [/Aut�nomo/g, 'Autónomo'],
  [/aut�noma/g, 'autónoma'],
  [/AUT�NOMA/g, 'AUTÓNOMA'],
  [/Aut�noma/g, 'Autónoma'],
  [/espec�fico/g, 'específico'],
  [/ESPEC�FICO/g, 'ESPECÍFICO'],
  [/Espec�fico/g, 'Específico'],
  [/espec�fica/g, 'específica'],
  [/ESPEC�FICA/g, 'ESPECÍFICA'],
  [/Espec�fica/g, 'Específica'],
  [/cient�fico/g, 'científico'],
  [/CIENT�FICO/g, 'CIENTÍFICO'],
  [/Cient�fico/g, 'Científico'],
  [/cient�fica/g, 'científica'],
  [/CIENT�FICA/g, 'CIENTÍFICA'],
  [/Cient�fica/g, 'Científica'],
  [/magn�fico/g, 'magnífico'],
  [/MAGN�FICO/g, 'MAGNÍFICO'],
  [/magn�fica/g, 'magnífica'],
  [/pac�fico/g, 'pacífico'],
  [/PAC�FICO/g, 'PACÍFICO'],
  [/Pac�fico/g, 'Pacífico'],
  [/pac�fica/g, 'pacífica'],
  [/PAC�FICA/g, 'PACÍFICA'],

  // Common words with accents
  [/tambi�n/g, 'también'],
  [/TAMBI�N/g, 'TAMBIÉN'],
  [/Tambi�n/g, 'También'],
  [/m�s/g, 'más'],
  [/M�S/g, 'MÁS'],
  [/M�s/g, 'Más'],
  [/seg�n/g, 'según'],
  [/SEG�N/g, 'SEGÚN'],
  [/Seg�n/g, 'Según'],
  [/as�/g, 'así'],
  [/AS�/g, 'ASÍ'],
  [/As�/g, 'Así'],
  [/dem�s/g, 'demás'],
  [/DEM�S/g, 'DEMÁS'],
  [/Dem�s/g, 'Demás'],
  [/adem�s/g, 'además'],
  [/ADEM�S/g, 'ADEMÁS'],
  [/Adem�s/g, 'Además'],
  [/despu�s/g, 'después'],
  [/DESPU�S/g, 'DESPUÉS'],
  [/Despu�s/g, 'Después'],
  [/a trav�s/g, 'a través'],
  [/A TRAV�S/g, 'A TRAVÉS'],
  [/A trav�s/g, 'A través'],
  [/qui�n/g, 'quién'],
  [/QUI�N/g, 'QUIÉN'],
  [/Qui�n/g, 'Quién'],
  [/qui�nes/g, 'quiénes'],
  [/c�mo/g, 'cómo'],
  [/C�MO/g, 'CÓMO'],
  [/C�mo/g, 'Cómo'],
  [/d�nde/g, 'dónde'],
  [/D�NDE/g, 'DÓNDE'],
  [/D�nde/g, 'Dónde'],
  [/cu�ndo/g, 'cuándo'],
  [/CU�NDO/g, 'CUÁNDO'],
  [/Cu�ndo/g, 'Cuándo'],
  [/qu�/g, 'qué'],
  [/QU�/g, 'QUÉ'],
  [/Qu�/g, 'Qué'],
  [/por qu�/g, 'por qué'],
  [/POR QU�/g, 'POR QUÉ'],
  [/Por qu�/g, 'Por qué'],
  [/cu�l/g, 'cuál'],
  [/CU�L/g, 'CUÁL'],
  [/Cu�l/g, 'Cuál'],
  [/cu�les/g, 'cuáles'],
  [/CU�LES/g, 'CUÁLES'],
  [/Cu�les/g, 'Cuáles'],
  [/cu�nto/g, 'cuánto'],
  [/CU�NTO/g, 'CUÁNTO'],
  [/Cu�nto/g, 'Cuánto'],
  [/est�/g, 'está'],
  [/EST�/g, 'ESTÁ'],
  [/Est�/g, 'Está'],
  [/est�n/g, 'están'],
  [/EST�N/g, 'ESTÁN'],
  [/Est�n/g, 'Están'],
  [/est�s/g, 'estás'],
  [/ser�/g, 'será'],
  [/SER�/g, 'SERÁ'],
  [/Ser�/g, 'Será'],
  [/ser�n/g, 'serán'],
  [/SER�N/g, 'SERÁN'],
  [/Ser�n/g, 'Serán'],
  [/podr�/g, 'podrá'],
  [/PODR�/g, 'PODRÁ'],
  [/Podr�/g, 'Podrá'],
  [/podr�n/g, 'podrán'],
  [/PODR�N/g, 'PODRÁN'],
  [/Podr�n/g, 'Podrán'],
  [/deber�/g, 'deberá'],
  [/DEBER�/g, 'DEBERÁ'],
  [/Deber�/g, 'Deberá'],
  [/deber�n/g, 'deberán'],
  [/DEBER�N/g, 'DEBERÁN'],
  [/Deber�n/g, 'Deberán'],
  [/tendr�/g, 'tendrá'],
  [/TENDR�/g, 'TENDRÁ'],
  [/Tendr�/g, 'Tendrá'],
  [/tendr�n/g, 'tendrán'],
  [/TENDR�N/g, 'TENDRÁN'],
  [/Tendr�n/g, 'Tendrán'],
  [/har�/g, 'hará'],
  [/HAR�/g, 'HARÁ'],
  [/har�n/g, 'harán'],
  [/HAR�N/g, 'HARÁN'],
  [/dar�/g, 'dará'],
  [/DAR�/g, 'DARÁ'],
  [/Dar�/g, 'Dará'],
  [/dar�n/g, 'darán'],
  [/DAR�N/g, 'DARÁN'],
  [/pondr�/g, 'pondrá'],
  [/PONDR�/g, 'PONDRÁ'],
  [/saldr�/g, 'saldrá'],
  [/SALDR�/g, 'SALDRÁ'],
  [/vendr�/g, 'vendrá'],
  [/VENDR�/g, 'VENDRÁ'],
  [/querr�/g, 'querrá'],
  [/QUERR�/g, 'QUERRÁ'],
  [/sabr�/g, 'sabrá'],
  [/SABR�/g, 'SABRÁ'],
  [/habr�/g, 'habrá'],
  [/HABR�/g, 'HABRÁ'],
  [/Habr�/g, 'Habrá'],
  [/valdr�/g, 'valdrá'],
  [/VALDR�/g, 'VALDRÁ'],
  [/cabr�/g, 'cabrá'],

  // Past tense verbs (common)
  [/aprob�/g, 'aprobó'],
  [/APROB�/g, 'APROBÓ'],
  [/public�/g, 'publicó'],
  [/PUBLIC�/g, 'PUBLICÓ'],
  [/modific�/g, 'modificó'],
  [/MODIFIC�/g, 'MODIFICÓ'],
  [/declar�/g, 'declaró'],
  [/DECLAR�/g, 'DECLARÓ'],
  [/estableci�/g, 'estableció'],
  [/ESTABLECI�/g, 'ESTABLECIÓ'],
  [/dispuso/g, 'dispuso'], // Usually OK
  [/se�al�/g, 'señaló'],
  [/SE�AL�/g, 'SEÑALÓ'],
  [/design�/g, 'designó'],
  [/DESIGN�/g, 'DESIGNÓ'],
  [/cre�/g, 'creó'],
  [/CRE�/g, 'CREÓ'],
  [/dict�/g, 'dictó'],
  [/DICT�/g, 'DICTÓ'],
  [/orden�/g, 'ordenó'],
  [/ORDEN�/g, 'ORDENÓ'],
  [/autoriz�/g, 'autorizó'],
  [/AUTORIZ�/g, 'AUTORIZÓ'],
  [/facult�/g, 'facultó'],
  [/FACULT�/g, 'FACULTÓ'],
  [/derog�/g, 'derogó'],
  [/DEROG�/g, 'DEROGÓ'],
  [/sustituy�/g, 'sustituyó'],
  [/SUSTITUY�/g, 'SUSTITUYÓ'],
  [/incluy�/g, 'incluyó'],
  [/INCLUY�/g, 'INCLUYÓ'],
  [/concluy�/g, 'concluyó'],
  [/CONCLUY�/g, 'CONCLUYÓ'],

  // Names and titles
  [/Jos�/g, 'José'],
  [/JOS�/g, 'JOSÉ'],
  [/Mar�a/g, 'María'],
  [/MAR�A/g, 'MARÍA'],
  [/Garc�a/g, 'García'],
  [/GARC�A/g, 'GARCÍA'],
  [/Gonz�lez/g, 'González'],
  [/GONZ�LEZ/g, 'GONZÁLEZ'],
  [/Rodr�guez/g, 'Rodríguez'],
  [/RODR�GUEZ/g, 'RODRÍGUEZ'],
  [/Fern�ndez/g, 'Fernández'],
  [/FERN�NDEZ/g, 'FERNÁNDEZ'],
  [/L�pez/g, 'López'],
  [/L�PEZ/g, 'LÓPEZ'],
  [/Mart�nez/g, 'Martínez'],
  [/MART�NEZ/g, 'MARTÍNEZ'],
  [/S�nchez/g, 'Sánchez'],
  [/S�NCHEZ/g, 'SÁNCHEZ'],
  [/P�rez/g, 'Pérez'],
  [/P�REZ/g, 'PÉREZ'],
  [/Ram�rez/g, 'Ramírez'],
  [/RAM�REZ/g, 'RAMÍREZ'],
  [/Jim�nez/g, 'Jiménez'],
  [/JIM�NEZ/g, 'JIMÉNEZ'],
  [/Hern�ndez/g, 'Hernández'],
  [/HERN�NDEZ/g, 'HERNÁNDEZ'],
  [/D�az/g, 'Díaz'],
  [/D�AZ/g, 'DÍAZ'],
  [/N��ez/g, 'Núñez'],
  [/N��EZ/g, 'NÚÑEZ'],
  [/Ord��ez/g, 'Ordóñez'],
  [/ORD��EZ/g, 'ORDÓÑEZ'],
  [/Ya��ez/g, 'Yáñez'],
  [/YA��EZ/g, 'YÁÑEZ'],
  [/Ib��ez/g, 'Ibáñez'],
  [/IB��EZ/g, 'IBÁÑEZ'],
  [/Mu�oz/g, 'Muñoz'],
  [/MU�OZ/g, 'MUÑOZ'],
  [/Ba�os/g, 'Baños'],
  [/BA�OS/g, 'BAÑOS'],
  [/Due�as/g, 'Dueñas'],
  [/DUE�AS/g, 'DUEÑAS'],
  [/Due�o/g, 'Dueño'],
  [/DUE�O/g, 'DUEÑO'],
  [/due�o/g, 'dueño'],
  [/Casta�eda/g, 'Castañeda'],
  [/CASTA�EDA/g, 'CASTAÑEDA'],
  [/Pi�a/g, 'Piña'],
  [/PI�A/g, 'PIÑA'],
  [/Vi�a/g, 'Viña'],
  [/VI�A/g, 'VIÑA'],
  [/Monta�a/g, 'Montaña'],
  [/MONTA�A/g, 'MONTAÑA'],
  [/monta�a/g, 'montaña'],
  [/Espa�a/g, 'España'],
  [/ESPA�A/g, 'ESPAÑA'],
  [/espa�a/g, 'españa'],
  [/espa�ol/g, 'español'],
  [/ESPA�OL/g, 'ESPAÑOL'],
  [/Espa�ol/g, 'Español'],
  [/espa�ola/g, 'española'],
  [/ESPA�OLA/g, 'ESPAÑOLA'],
  [/Espa�ola/g, 'Española'],
  [/compa��a/g, 'compañía'],
  [/COMPA��A/g, 'COMPAÑÍA'],
  [/Compa��a/g, 'Compañía'],
  [/campa�a/g, 'campaña'],
  [/CAMPA�A/g, 'CAMPAÑA'],
  [/Campa�a/g, 'Campaña'],
  [/ense�anza/g, 'enseñanza'],
  [/ENSE�ANZA/g, 'ENSEÑANZA'],
  [/Ense�anza/g, 'Enseñanza'],
  [/ni�o/g, 'niño'],
  [/NI�O/g, 'NIÑO'],
  [/Ni�o/g, 'Niño'],
  [/ni�a/g, 'niña'],
  [/NI�A/g, 'NIÑA'],
  [/Ni�a/g, 'Niña'],
  [/ni�os/g, 'niños'],
  [/NI�OS/g, 'NIÑOS'],
  [/Ni�os/g, 'Niños'],
  [/ni�as/g, 'niñas'],
  [/NI�AS/g, 'NIÑAS'],
  [/Ni�as/g, 'Niñas'],
  [/sue�o/g, 'sueño'],
  [/SUE�O/g, 'SUEÑO'],
  [/due�a/g, 'dueña'],
  [/DUE�A/g, 'DUEÑA'],
  [/peque�o/g, 'pequeño'],
  [/PEQUE�O/g, 'PEQUEÑO'],
  [/Peque�o/g, 'Pequeño'],
  [/peque�a/g, 'pequeña'],
  [/PEQUE�A/g, 'PEQUEÑA'],
  [/Peque�a/g, 'Pequeña'],
  [/da�o/g, 'daño'],
  [/DA�O/g, 'DAÑO'],
  [/Da�o/g, 'Daño'],
  [/da�os/g, 'daños'],
  [/DA�OS/g, 'DAÑOS'],
  [/enga�o/g, 'engaño'],
  [/ENGA�O/g, 'ENGAÑO'],
  [/reta�o/g, 'retaño'],
  [/empe�o/g, 'empeño'],
  [/EMPE�O/g, 'EMPEÑO'],
  [/desempe�o/g, 'desempeño'],
  [/DESEMPE�O/g, 'DESEMPEÑO'],
  [/Desempe�o/g, 'Desempeño'],
  [/compa�ero/g, 'compañero'],
  [/COMPA�ERO/g, 'COMPAÑERO'],
  [/compa�era/g, 'compañera'],
  [/COMPA�ERA/g, 'COMPAÑERA'],
  [/oto�o/g, 'otoño'],
  [/OTO�O/g, 'OTOÑO'],
  [/caba�a/g, 'cabaña'],
  [/CABA�A/g, 'CABAÑA'],
  [/ara�a/g, 'araña'],
  [/ARA�A/g, 'ARAÑA'],
  [/cuca�a/g, 'cucaña'],
  [/mara�a/g, 'maraña'],
  [/ciga�a/g, 'cigarra'], // might be different
  [/CIGA�A/g, 'CIGARRA'],
  [/rega�o/g, 'regaño'],
  [/REGA�O/g, 'REGAÑO'],
  [/extra�o/g, 'extraño'],
  [/EXTRA�O/g, 'EXTRAÑO'],
  [/Extra�o/g, 'Extraño'],
  [/extra�a/g, 'extraña'],
  [/EXTRA�A/g, 'EXTRAÑA'],
  [/Extra�a/g, 'Extraña'],
  [/tama�o/g, 'tamaño'],
  [/TAMA�O/g, 'TAMAÑO'],
  [/Tama�o/g, 'Tamaño'],
  [/rega�a/g, 'regaña'],
  [/rega�ar/g, 'regañar'],
  [/orde�ar/g, 'ordeñar'],
  [/so�ar/g, 'soñar'],
  [/SO�AR/g, 'SOÑAR'],
  [/enga�ar/g, 'engañar'],
  [/ENGA�AR/g, 'ENGAÑAR'],
  [/ense�ar/g, 'enseñar'],
  [/ENSE�AR/g, 'ENSEÑAR'],
  [/empe�ar/g, 'empeñar'],
  [/EMPE�AR/g, 'EMPEÑAR'],
  [/desempe�ar/g, 'desempeñar'],
  [/DESEMPE�AR/g, 'DESEMPEÑAR'],
  [/acompa�ar/g, 'acompañar'],
  [/ACOMPA�AR/g, 'ACOMPAÑAR'],
  [/ba�ar/g, 'bañar'],
  [/BA�AR/g, 'BAÑAR'],
  [/da�ar/g, 'dañar'],
  [/DA�AR/g, 'DAÑAR'],
  [/rega�ar/g, 'regañar'],
  [/REGA�AR/g, 'REGAÑAR'],
  [/extra�ar/g, 'extrañar'],
  [/EXTRA�AR/g, 'EXTRAÑAR'],

  // Places
  [/Per�/g, 'Perú'],
  [/PER�/g, 'PERÚ'],
  [/per�/g, 'perú'],
  [/Bogot�/g, 'Bogotá'],
  [/BOGOT�/g, 'BOGOTÁ'],
  [/Panam�/g, 'Panamá'],
  [/PANAM�/g, 'PANAMÁ'],
  [/M�xico/g, 'México'],
  [/M�XICO/g, 'MÉXICO'],
  [/Am�rica/g, 'América'],
  [/AM�RICA/g, 'AMÉRICA'],
  [/Am�rica/g, 'América'],
  [/�frica/g, 'África'],
  [/�FRICA/g, 'ÁFRICA'],
  [/Asia/g, 'Asia'], // Usually OK
  [/Apur�mac/g, 'Apurímac'],
  [/APUR�MAC/g, 'APURÍMAC'],
  [/Ayacucho/g, 'Ayacucho'], // Usually OK
  [/Hu�nuco/g, 'Huánuco'],
  [/HU�NUCO/g, 'HUÁNUCO'],
  [/Jun�n/g, 'Junín'],
  [/JUN�N/g, 'JUNÍN'],
  [/San Mart�n/g, 'San Martín'],
  [/SAN MART�N/g, 'SAN MARTÍN'],
  [/Tumbes/g, 'Tumbes'], // Usually OK
  [/Ucayali/g, 'Ucayali'], // Usually OK
  [/Hu�ncayo/g, 'Huancayo'], // Note: no accent in Spanish
  [/Chiclayo/g, 'Chiclayo'], // Usually OK
  [/Trujillo/g, 'Trujillo'], // Usually OK
  [/Arequipa/g, 'Arequipa'], // Usually OK
  [/Cusco/g, 'Cusco'], // Usually OK
  [/Cuzco/g, 'Cuzco'], // Usually OK
  [/Tacna/g, 'Tacna'], // Usually OK
  [/Iquitos/g, 'Iquitos'], // Usually OK
  [/Puno/g, 'Puno'], // Usually OK
  [/Piura/g, 'Piura'], // Usually OK
  [/Callao/g, 'Callao'], // Usually OK
  [/Cajamarca/g, 'Cajamarca'], // Usually OK
  [/Lambayeque/g, 'Lambayeque'], // Usually OK
  [/Loreto/g, 'Loreto'], // Usually OK
  [/Madre de Dios/g, 'Madre de Dios'], // Usually OK
  [/Moquegua/g, 'Moquegua'], // Usually OK
  [/Pasco/g, 'Pasco'], // Usually OK

  // More common words
  [/informaci�n/g, 'información'],
  [/garant�a/g, 'garantía'],
  [/GARANT�A/g, 'GARANTÍA'],
  [/Garant�a/g, 'Garantía'],
  [/garant�as/g, 'garantías'],
  [/GARANT�AS/g, 'GARANTÍAS'],
  [/autonom�a/g, 'autonomía'],
  [/AUTONOM�A/g, 'AUTONOMÍA'],
  [/Autonom�a/g, 'Autonomía'],
  [/econom�a/g, 'economía'],
  [/ECONOM�A/g, 'ECONOMÍA'],
  [/Econom�a/g, 'Economía'],
  [/biolog�a/g, 'biología'],
  [/BIOLOG�A/g, 'BIOLOGÍA'],
  [/Biolog�a/g, 'Biología'],
  [/tecnolog�a/g, 'tecnología'],
  [/TECNOLOG�A/g, 'TECNOLOGÍA'],
  [/Tecnolog�a/g, 'Tecnología'],
  [/metodolog�a/g, 'metodología'],
  [/METODOLOG�A/g, 'METODOLOGÍA'],
  [/Metodolog�a/g, 'Metodología'],
  [/ideolog�a/g, 'ideología'],
  [/IDEOLOG�A/g, 'IDEOLOGÍA'],
  [/geolog�a/g, 'geología'],
  [/GEOLOG�A/g, 'GEOLOGÍA'],
  [/Geolog�a/g, 'Geología'],
  [/psicolog�a/g, 'psicología'],
  [/PSICOLOG�A/g, 'PSICOLOGÍA'],
  [/Psicolog�a/g, 'Psicología'],
  [/sociolog�a/g, 'sociología'],
  [/SOCIOLOG�A/g, 'SOCIOLOGÍA'],
  [/Sociolog�a/g, 'Sociología'],
  [/antropolog�a/g, 'antropología'],
  [/ANTROPOLOG�A/g, 'ANTROPOLOGÍA'],
  [/zoolog�a/g, 'zoología'],
  [/ZOOLOG�A/g, 'ZOOLOGÍA'],
  [/ecolog�a/g, 'ecología'],
  [/ECOLOG�A/g, 'ECOLOGÍA'],
  [/Ecolog�a/g, 'Ecología'],
  [/arqueolog�a/g, 'arqueología'],
  [/ARQUEOLOG�A/g, 'ARQUEOLOGÍA'],
  [/Arqueolog�a/g, 'Arqueología'],
  [/farmacolog�a/g, 'farmacología'],
  [/FARMACOLOG�A/g, 'FARMACOLOGÍA'],
  [/cronolog�a/g, 'cronología'],
  [/CRONOLOG�A/g, 'CRONOLOGÍA'],
  [/energ�a/g, 'energía'],
  [/ENERG�A/g, 'ENERGÍA'],
  [/Energ�a/g, 'Energía'],
  [/cirug�a/g, 'cirugía'],
  [/CIRUG�A/g, 'CIRUGÍA'],
  [/Cirug�a/g, 'Cirugía'],
  [/estrategia/g, 'estrategia'], // Usually OK
  [/democracia/g, 'democracia'], // Usually OK
  [/burocracia/g, 'burocracia'], // Usually OK
  [/autocracia/g, 'autocracia'], // Usually OK
  [/aristocracia/g, 'aristocracia'], // Usually OK
  [/hipocres�a/g, 'hipocresía'],
  [/HIPOCRES�A/g, 'HIPOCRESÍA'],
  [/cortes�a/g, 'cortesía'],
  [/CORTES�A/g, 'CORTESÍA'],
  [/poes�a/g, 'poesía'],
  [/POES�A/g, 'POESÍA'],
  [/Poes�a/g, 'Poesía'],
  [/fantas�a/g, 'fantasía'],
  [/FANTAS�A/g, 'FANTASÍA'],
  [/Fantas�a/g, 'Fantasía'],
  [/iron�a/g, 'ironía'],
  [/IRON�A/g, 'IRONÍA'],
  [/armon�a/g, 'armonía'],
  [/ARMON�A/g, 'ARMONÍA'],
  [/Armon�a/g, 'Armonía'],
  [/autonom�a/g, 'autonomía'],
  [/anatom�a/g, 'anatomía'],
  [/ANATOM�A/g, 'ANATOMÍA'],
  [/Anatom�a/g, 'Anatomía'],
  [/astronom�a/g, 'astronomía'],
  [/ASTRONOM�A/g, 'ASTRONOMÍA'],
  [/Astronom�a/g, 'Astronomía'],
  [/gastronom�a/g, 'gastronomía'],
  [/GASTRONOM�A/g, 'GASTRONOMÍA'],
  [/agronom�a/g, 'agronomía'],
  [/AGRONOM�A/g, 'AGRONOMÍA'],
  [/Agronom�a/g, 'Agronomía'],
  [/minor�a/g, 'minoría'],
  [/MINOR�A/g, 'MINORÍA'],
  [/Minor�a/g, 'Minoría'],
  [/mayor�a/g, 'mayoría'],
  [/MAYOR�A/g, 'MAYORÍA'],
  [/Mayor�a/g, 'Mayoría'],
  [/tesorer�a/g, 'tesorería'],
  [/TESORER�A/g, 'TESORERÍA'],
  [/Tesorer�a/g, 'Tesorería'],
  [/secretar�a/g, 'secretaría'],
  [/SECRETAR�A/g, 'SECRETARÍA'],
  [/Secretar�a/g, 'Secretaría'],
  [/notario/g, 'notario'], // Usually OK
  [/notar�a/g, 'notaría'],
  [/NOTAR�A/g, 'NOTARÍA'],
  [/Notar�a/g, 'Notaría'],
  [/categor�a/g, 'categoría'],
  [/CATEGOR�A/g, 'CATEGORÍA'],
  [/Categor�a/g, 'Categoría'],
  [/alegor�a/g, 'alegoría'],
  [/ALEGOR�A/g, 'ALEGORÍA'],
  [/teor�a/g, 'teoría'],
  [/TEOR�A/g, 'TEORÍA'],
  [/Teor�a/g, 'Teoría'],
  [/memoria/g, 'memoria'], // Usually OK
  [/historia/g, 'historia'], // Usually OK
  [/victoria/g, 'victoria'], // Usually OK
  [/gloria/g, 'gloria'], // Usually OK
  [/euforia/g, 'euforia'], // Usually OK
  [/disforia/g, 'disforia'], // Usually OK
  [/alegr�a/g, 'alegría'],
  [/ALEGR�A/g, 'ALEGRÍA'],
  [/Alegr�a/g, 'Alegría'],
  [/regidur�a/g, 'regiduría'],
  [/REGIDUR�A/g, 'REGIDURÍA'],
  [/Regidur�a/g, 'Regiduría'],
  [/tutor�a/g, 'tutoría'],
  [/TUTOR�A/g, 'TUTORÍA'],
  [/autor�a/g, 'autoría'],
  [/AUTOR�A/g, 'AUTORÍA'],
  [/fiscal�a/g, 'fiscalía'],
  [/FISCAL�A/g, 'FISCALÍA'],
  [/Fiscal�a/g, 'Fiscalía'],
  [/alcald�a/g, 'alcaldía'],
  [/ALCALD�A/g, 'ALCALDÍA'],
  [/Alcald�a/g, 'Alcaldía'],
  [/ciudadan�a/g, 'ciudadanía'],
  [/CIUDADAN�A/g, 'CIUDADANÍA'],
  [/Ciudadan�a/g, 'Ciudadanía'],
  [/soberan�a/g, 'soberanía'],
  [/SOBERAN�A/g, 'SOBERANÍA'],
  [/Soberan�a/g, 'Soberanía'],
  [/campesinado/g, 'campesinado'], // Usually OK
  [/capellan�a/g, 'capellanía'],
  [/CAPELLAN�A/g, 'CAPELLANÍA'],
  [/ciudadela/g, 'ciudadela'], // Usually OK

  // More everyday words
  [/todav�a/g, 'todavía'],
  [/TODAV�A/g, 'TODAVÍA'],
  [/Todav�a/g, 'Todavía'],
  [/incre�ble/g, 'increíble'],
  [/INCRE�BLE/g, 'INCREÍBLE'],
  [/posible/g, 'posible'], // Usually OK
  [/imposible/g, 'imposible'], // Usually OK
  [/cre�ble/g, 'creíble'],
  [/CRE�BLE/g, 'CREÍBLE'],
  [/viable/g, 'viable'], // Usually OK
  [/aceptable/g, 'aceptable'], // Usually OK
  [/responsable/g, 'responsable'], // Usually OK
  [/razonable/g, 'razonable'], // Usually OK
  [/considerable/g, 'considerable'], // Usually OK
  [/comparable/g, 'comparable'], // Usually OK
  [/deseable/g, 'deseable'], // Usually OK
  [/�til/g, 'útil'],
  [/�TIL/g, 'ÚTIL'],
  [/in�til/g, 'inútil'],
  [/IN�TIL/g, 'INÚTIL'],
  [/d�bil/g, 'débil'],
  [/D�BIL/g, 'DÉBIL'],
  [/f�cil/g, 'fácil'],
  [/F�CIL/g, 'FÁCIL'],
  [/dif�cil/g, 'difícil'],
  [/DIF�CIL/g, 'DIFÍCIL'],
  [/fr�gil/g, 'frágil'],
  [/FR�GIL/g, 'FRÁGIL'],
  [/�gil/g, 'ágil'],
  [/�GIL/g, 'ÁGIL'],
  [/m�vil/g, 'móvil'],
  [/M�VIL/g, 'MÓVIL'],
  [/inm�vil/g, 'inmóvil'],
  [/INM�VIL/g, 'INMÓVIL'],
  [/autom�vil/g, 'automóvil'],
  [/AUTOM�VIL/g, 'AUTOMÓVIL'],
  [/Autom�vil/g, 'Automóvil'],
  [/hostil/g, 'hostil'], // Usually OK
  [/civil/g, 'civil'], // Usually OK
  [/juvenil/g, 'juvenil'], // Usually OK
  [/senil/g, 'senil'], // Usually OK
  [/viril/g, 'viril'], // Usually OK
  [/f�rtil/g, 'fértil'],
  [/F�RTIL/g, 'FÉRTIL'],
  [/est�ril/g, 'estéril'],
  [/EST�RIL/g, 'ESTÉRIL'],
  [/vol�til/g, 'volátil'],
  [/VOL�TIL/g, 'VOLÁTIL'],
  [/vers�til/g, 'versátil'],
  [/VERS�TIL/g, 'VERSÁTIL'],
  [/textil/g, 'textil'], // Usually OK
  [/sutil/g, 'sutil'], // Usually OK
  [/proyectil/g, 'proyectil'], // Usually OK
  [/�cido/g, 'ácido'],
  [/�CIDO/g, 'ÁCIDO'],
  [/l�quido/g, 'líquido'],
  [/L�QUIDO/g, 'LÍQUIDO'],
  [/L�quido/g, 'Líquido'],
  [/s�lido/g, 'sólido'],
  [/S�LIDO/g, 'SÓLIDO'],
  [/S�lido/g, 'Sólido'],
  [/r�pido/g, 'rápido'],
  [/R�PIDO/g, 'RÁPIDO'],
  [/R�pido/g, 'Rápido'],
  [/h�medo/g, 'húmedo'],
  [/H�MEDO/g, 'HÚMEDO'],
  [/t�mido/g, 'tímido'],
  [/T�MIDO/g, 'TÍMIDO'],
  [/v�lido/g, 'válido'],
  [/V�LIDO/g, 'VÁLIDO'],
  [/V�lido/g, 'Válido'],
  [/inv�lido/g, 'inválido'],
  [/INV�LIDO/g, 'INVÁLIDO'],
  [/c�lido/g, 'cálido'],
  [/C�LIDO/g, 'CÁLIDO'],
  [/p�lido/g, 'pálido'],
  [/P�LIDO/g, 'PÁLIDO'],
  [/s�rdido/g, 'sórdido'],
  [/S�RDIDO/g, 'SÓRDIDO'],
  [/h�brido/g, 'híbrido'],
  [/H�BRIDO/g, 'HÍBRIDO'],
  [/H�brido/g, 'Híbrido'],
  [/�rido/g, 'árido'],
  [/�RIDO/g, 'ÁRIDO'],
  [/c�ndido/g, 'cándido'],
  [/C�NDIDO/g, 'CÁNDIDO'],
  [/esp�ritu/g, 'espíritu'],
  [/ESP�RITU/g, 'ESPÍRITU'],
  [/Esp�ritu/g, 'Espíritu'],
  [/h�bito/g, 'hábito'],
  [/H�BITO/g, 'HÁBITO'],
  [/H�bito/g, 'Hábito'],
  [/�mbito/g, 'ámbito'],
  [/�MBITO/g, 'ÁMBITO'],
  [/cr�dito/g, 'crédito'],
  [/CR�DITO/g, 'CRÉDITO'],
  [/Cr�dito/g, 'Crédito'],
  [/d�ficit/g, 'déficit'],
  [/D�FICIT/g, 'DÉFICIT'],
  [/D�ficit/g, 'Déficit'],
  [/l�mite/g, 'límite'],
  [/L�MITE/g, 'LÍMITE'],
  [/L�mite/g, 'Límite'],
  [/tr�mite/g, 'trámite'],
  [/tr�nsito/g, 'tránsito'],
  [/TR�NSITO/g, 'TRÁNSITO'],
  [/Tr�nsito/g, 'Tránsito'],
  [/dep�sito/g, 'depósito'],
  [/DEP�SITO/g, 'DEPÓSITO'],
  [/Dep�sito/g, 'Depósito'],
  [/prop�sito/g, 'propósito'],
  [/PROP�SITO/g, 'PROPÓSITO'],
  [/Prop�sito/g, 'Propósito'],
  [/requisito/g, 'requisito'], // Usually OK
  [/prerrequisito/g, 'prerrequisito'], // Usually OK
  [/ex�geno/g, 'exógeno'],
  [/EX�GENO/g, 'EXÓGENO'],
  [/end�geno/g, 'endógeno'],
  [/END�GENO/g, 'ENDÓGENO'],
  [/hom�logo/g, 'homólogo'],
  [/HOM�LOGO/g, 'HOMÓLOGO'],
  [/an�logo/g, 'análogo'],
  [/AN�LOGO/g, 'ANÁLOGO'],
  [/cat�logo/g, 'catálogo'],
  [/CAT�LOGO/g, 'CATÁLOGO'],
  [/Cat�logo/g, 'Catálogo'],
  [/di�logo/g, 'diálogo'],
  [/DI�LOGO/g, 'DIÁLOGO'],
  [/Di�logo/g, 'Diálogo'],
  [/ep�logo/g, 'epílogo'],
  [/EP�LOGO/g, 'EPÍLOGO'],
  [/pr�logo/g, 'prólogo'],
  [/PR�LOGO/g, 'PRÓLOGO'],
  [/Pr�logo/g, 'Prólogo'],
  [/mon�logo/g, 'monólogo'],
  [/MON�LOGO/g, 'MONÓLOGO'],

  // Generic patterns - these should be last as they're less specific
  // Character + � + common suffix patterns
]

function getAllMdFiles(dir: string): string[] {
  const files: string[] = []
  for (const entry of readdirSync(dir)) {
    if (entry.startsWith('.')) continue
    const fullPath = join(dir, entry)
    const stat = statSync(fullPath)
    if (stat.isDirectory()) {
      files.push(...getAllMdFiles(fullPath))
    } else if (entry.endsWith('.md')) {
      files.push(fullPath)
    }
  }
  return files
}

function fixEncoding(content: string): string {
  let fixed = content
  for (const [pattern, replacement] of contextualFixes) {
    fixed = fixed.replace(pattern, replacement)
  }
  return fixed
}

async function main() {
  const leyesDir = process.argv[2] || join(process.cwd(), '../../leyes/pe')
  console.log(`Scanning directory: ${leyesDir}`)

  const files = getAllMdFiles(leyesDir)
  console.log(`Found ${files.length} markdown files`)

  let fixedCount = 0
  let totalReplacements = 0

  for (const file of files) {
    const content = readFileSync(file, 'utf-8')

    // Check if file has the replacement character
    if (!content.includes('�')) {
      continue
    }

    const fixed = fixEncoding(content)

    // Count remaining replacement characters
    const remainingBefore = (content.match(/�/g) || []).length
    const remainingAfter = (fixed.match(/�/g) || []).length
    const replacements = remainingBefore - remainingAfter

    if (replacements > 0) {
      writeFileSync(file, fixed, 'utf-8')
      fixedCount++
      totalReplacements += replacements
      console.log(
        `Fixed ${file.split('/').pop()}: ${replacements} replacements (${remainingAfter} remaining)`,
      )
    }
  }

  console.log('\nSummary:')
  console.log(`- Files processed: ${files.length}`)
  console.log(`- Files fixed: ${fixedCount}`)
  console.log(`- Total replacements: ${totalReplacements}`)
}

main().catch(console.error)
